rework infoBlitz and add VPN color
raspiblitz/raspiblitz pull request #1473
Opened 2020-08-21 19:45 UTC by ChuckNorrison

- fixed bugs with wrong variable syntax
- replaced 1 space intend with 2 spaces
- call ip route 8.8.8.8 to make public check
- skip netcat checks for VPN setup (tun0)
- new color cyan for VPN setup

2020-08-21 19:54 UTC, ChuckNorrison commented
the ip route 8.8.8.8 could replaced with any ip, it has not to be reachable, just match the routing table. so TOR should not have any problems with that check. maybe a fallback check to the old method could make sense. 

i dont like the tun0 hardcoded string but it should be fine

2020-08-22 10:29 UTC, ChuckNorrison commented
some findings here i want to add soon

2020-08-22 11:16 UTC, ChuckNorrison commented
got some issues with bash variable checks and syntax for data types. public_check seems fine for that data type expected. Please double check this :+1: 

```
Gathering Information (please wait) ...
INFO: active interface found: tun0
INFO: public port: 8333
INFO: VPN Setup was found
INFO: check VPN setup for lightning network...
INFO: ... succeeded
```

2020-08-22 16:04 UTC, frennkie commented
> fixed bugs with wrong variable syntax
> replaced 1 space intend with 2 spaces

It's hard to only identify these changes. Would you mind putting these in to a separate PR?

> call ip route 8.8.8.8 to make public check

I left a alternative suggestion in the review.

> skip netcat checks for VPN setup (tun0)
> new color cyan for VPN setup

I'm not entirely sure we want/need this (also why I'm asking to keep the changes separated).

2020-08-22 16:04 UTC, frennkie requested changes

2020-08-22 16:04 UTC, frennkie commented on home.admin/00infoBlitz.sh
> +network_active_if=$(ip route get 8.8.8.8 | awk  -- '{print $5}')
Looks a bit awkward to have a hard coded IP here... how about this:

`ip addr | awk '/state UP/ {print $2}' | sed 's/.$//' | head -n 1`

Or will that fail if multiple interfaces are up (e.g. eth0 and tun0 ) ? If it fails.. would 255.255.255.255 work instead of 8.8.8.8?

2020-08-22 17:42 UTC, ChuckNorrison commented on home.admin/00infoBlitz.sh
> +network_active_if=$(ip route get 8.8.8.8 | awk  -- '{print $5}')
i will test this with my setup, thanks

2020-08-23 07:16 UTC, ChuckNorrison commented
VPN Setup is not a use case, close

2020-08-23 07:16 UTC, closed without merging

2020-08-23 07:21 UTC, ChuckNorrison commented on home.admin/00infoBlitz.sh
> +network_active_if=$(ip route get 8.8.8.8 | awk  -- '{print $5}')
`ip addr | awk '/state UP/ {print $2}' | sed 's/.$//' | head -n 1`

results in eth0 than tun0.

2020-08-23 10:24 UTC, ChuckNorrison commented on home.admin/00infoBlitz.sh
> +network_active_if=$(ip route get 8.8.8.8 | awk  -- '{print $5}')
`ip route get 255.255.255.255 | awk  -- '{print $5}'`

works for me

2020-08-27 10:20 UTC, ChuckNorrison commented
After setup my LCD, i observed my INFO echos. That was not intended :) But i like the additional DEBUG echo. I will rework that solution after ip route get was accepted