use 'ip route get' over 'ip addr' for interface check
raspiblitz/raspiblitz pull request #1478
Opened 2020-08-23 10:52 UTC by ChuckNorrison

should be a more generic, more safe and faster solution without any port forwarding or firewall dependencies. Will support virtual and tunneled network interfaces (tun0 for OpenVPN)

2020-08-23 21:05 UTC, frennkie requested changes

2020-08-23 21:05 UTC, frennkie commented on home.admin/00infoBlitz.sh
> +network_active_if=$(ip route get 255.255.255.255 | awk -- '{print $4}')
missing a `| head -n 1` right..?

2020-08-25 11:34 UTC, ChuckNorrison commented
I tested this call on some systems with tunneled adapters, with wlan and with lan only. I did not tested this with multiple physical adapters. 

Did not tested this with TOR or IP2TOR solution. 

`ip route get 255.255.255.255 | awk -- '{print $4}' | head -n 1`

This should always result the correct interface on all systems.

2020-09-05 20:14 UTC, frennkie approved these changes

2020-09-05 20:14 UTC, merged