Grafana dashboard JSON
raspiblitz/raspiblitz pull request #1501
Opened 2020-08-30 15:46 UTC by PatrickScheich

2020-09-09 10:53 UTC, frennkie requested changes
This looks very good..! :-D


But I have added some comments and have some general remarks:

In the .json file you are using `"datasource": "InfluxDB"` - would you mind switching this to `"datasource": null,`. The reason for this is that on my setup I'm not using "InfluxDB" (but "InfluxDBRPi") and I had to replace this line to make it work. As far as I see it `null` will use the `default` entry. That sounds more "flexible" to me.

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +              "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" = 'cerberus') AND $timeFilter GROUP BY time(1m) fill(null
What is "cerberus"? I assume this is a hardcoded local value from your setup.

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +          "text": "DesertRetreatLN",
That's your node name, right? Please put something generic there (e.g. "raspblitz") or leave it emtpy. Same for next line.

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +        "definition": "SHOW TAG VALUES FROM \"system\" WITH KEY=host",
Can we use a measurement that's more specific to this server? So instead of "system" use e.g. "ln-info".

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +        "query": "SHOW TAG VALUES FROM \"system\" WITH KEY=host",
Can we use a measurement that's more specific to this server? So instead of "system" use e.g. "ln-info".

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/README.md
> +All telegraf switches and configuration variables. You may copy & paste them into your RaspiBlitz configuration at `/mnt/hdd/raspiblitz.conf`, after editing and provide the proper values matching you
s/provide/providing/   and s/matching/to match/

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/etc-telegraf/telegraf.d/telegraf_inputs.conf
> +  interfaces                  = ["eth0"]
I'm using `wlan0` on one my systems. And there might be other interface names (e.g. ensXX) on other devices types (e.g. vms). Can this be included automatically somehow?

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/README.md
> +sudo /home/admin/config.scripts/bonus.telegraf.sh on
Currently we usually don't run the full script with `sudo`. Please remove it and make sure it will work anyway.

2020-09-09 10:53 UTC, frennkie commented on home.admin/config.scripts/bonus.telegraf.sh
> +  echo "deb https://repos.influxdata.com/debian ${DISTRIB_ID} stable" > /etc/apt/sources.list.d/influxdb.list
This won't work if the script is not run with `sudo`. Use `| sudo tee -a /etc/apt/sources.list.d/influxdb.list >/dev/null` instead of `>`.

2020-09-09 10:53 UTC, frennkie commented on home.admin/assets/telegraf/etc-telegraf/telegraf.conf
> +hostname                    = ""
Please be aware that - for privacy reasons - the hostname of the RaspiBlitz might not be the LND node alias (but "raspberrypi"). If you have more that one RaspiBlitz reporting to the same InfluxDB this will get "messy". I use the "[agent].hostname to overwrite with the `hostname` value from raspiblitz.conf. Can you please add a `sed` command to the bonus script that will do this too?

2020-09-09 11:02 UTC, frennkie commented
The monitoring will spam the logs with errors if the `electrs` bonus feature is not enabled.

```
admin@raspberrypi:~ $ sudo journalctl -f -u telegraf
-- Logs begin at Wed 2020-09-09 08:56:44 BST. --
Sep 09 11:58:30 raspberrypi telegraf[14069]: 2020-09-09T10:58:30Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
Sep 09 11:58:40 raspberrypi telegraf[14069]: 2020-09-09T10:58:40Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
Sep 09 11:58:50 raspberrypi telegraf[14069]: 2020-09-09T10:58:50Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
Sep 09 11:59:00 raspberrypi telegraf[14069]: 2020-09-09T10:59:00Z E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:4224/metrics: Get "http://localhost:4224/metrics": dial tcp [::1]:4224: connect: connection refused
Sep 09 11:59:00 raspberrypi telegraf[14069]: 2020-09-09T10:59:00Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
Sep 09 11:59:10 raspberrypi telegraf[14069]: 2020-09-09T10:59:10Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
```

I think the best way to handle this is add another command to `bonus.telegraf.sh` that is able to add and remove the eletrcs specific monitoring as needed.

2020-09-09 11:09 UTC, frennkie commented
Do you have any thoughts on a retention policy? Right now this is stored with full precision infinitely, right?

2020-09-09 12:59 UTC, PatrickScheich commented
@frennkie thanks for the comments, I will incorporate the changes and add them to this PR
that might take a bit

2020-09-09 13:08 UTC, frennkie commented
Sounds good.. We want to include this in 1.7 which still has time.. 😉

2020-10-01 22:34 UTC, PatrickScheich commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +              "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\")AS \"system\" FROM \"autogen\".\"cpu\" WHERE (\"host\" = 'cerberus') AND $timeFilter GROUP BY time(1m) fill(null
I removed any references to my local host from that json file

2020-10-01 22:35 UTC, PatrickScheich commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +        "definition": "SHOW TAG VALUES FROM \"system\" WITH KEY=host",
implemented

2020-10-01 22:43 UTC, PatrickScheich commented on home.admin/assets/telegraf/README.md
> +All telegraf switches and configuration variables. You may copy & paste them into your RaspiBlitz configuration at `/mnt/hdd/raspiblitz.conf`, after editing and provide the proper values matching you
included into README.md

2020-10-01 22:43 UTC, PatrickScheich commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +        "query": "SHOW TAG VALUES FROM \"system\" WITH KEY=host",
implemented

2020-10-01 22:45 UTC, PatrickScheich commented on home.admin/assets/telegraf/README.md
> +sudo /home/admin/config.scripts/bonus.telegraf.sh on
done

2020-10-01 22:47 UTC, PatrickScheich commented on home.admin/assets/telegraf/etc-telegraf/telegraf.d/telegraf_inputs.conf
> +  interfaces                  = ["eth0"]
thid might be a bit tricky...i wil try to come up with some solution

2020-10-01 22:54 UTC, PatrickScheich commented on home.admin/config.scripts/bonus.telegraf.sh
> +  echo "deb https://repos.influxdata.com/debian ${DISTRIB_ID} stable" > /etc/apt/sources.list.d/influxdb.list
implemented as suggested

2020-10-01 23:02 UTC, PatrickScheich commented on home.admin/assets/telegraf/etc-telegraf/telegraf.conf
> +hostname                    = ""
I did not get that, I may not understand the context corecct...

When will the "messy" situation occur?

We have several RaspiBlitz nodes in the same network, reporting to the same InfluxDB.
Isnt it necessary that each of them had a individual (network unique) hostname?

2020-10-01 23:05 UTC, PatrickScheich commented
> 
> 
> The monitoring will spam the logs with errors if the `electrs` bonus feature is not enabled.
> 
> ```
> admin@raspberrypi:~ $ sudo journalctl -f -u telegraf
> -- Logs begin at Wed 2020-09-09 08:56:44 BST. --
> Sep 09 11:58:30 raspberrypi telegraf[14069]: 2020-09-09T10:58:30Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
> Sep 09 11:58:40 raspberrypi telegraf[14069]: 2020-09-09T10:58:40Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
> Sep 09 11:58:50 raspberrypi telegraf[14069]: 2020-09-09T10:58:50Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
> Sep 09 11:59:00 raspberrypi telegraf[14069]: 2020-09-09T10:59:00Z E! [inputs.prometheus] Error in plugin: error making HTTP request to http://localhost:4224/metrics: Get "http://localhost:4224/metrics": dial tcp [::1]:4224: connect: connection refused
> Sep 09 11:59:00 raspberrypi telegraf[14069]: 2020-09-09T10:59:00Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
> Sep 09 11:59:10 raspberrypi telegraf[14069]: 2020-09-09T10:59:10Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 3:39: "service-uptime,service=electrs uptime="
> ```
> 
> I think the best way to handle this is add another command to `bonus.telegraf.sh` that is able to add and remove the eletrcs specific monitoring as needed.
> 
> Also affects: `/etc/telegraf/getserviceuptime.sh`

that will take me a bit...I understand the situation and will come up with some solution....

2020-10-03 20:10 UTC, PatrickScheich commented on home.admin/assets/telegraf/etc-telegraf/telegraf.d/telegraf_inputs.conf
> +  interfaces                  = ["eth0"]
well it might be quite easy in the end when omitting the "interfaces" line telegraf will collect metrics from all available interfaces automatically. I might create a bit more clutter in the database...but that seems to be no problem

2020-10-03 20:12 UTC, PatrickScheich commented on home.admin/assets/telegraf/raspiblitz-grafana-dashboard.json
> +          "text": "DesertRetreatLN",
I set it to null so it should be select able

2020-10-07 10:52 UTC, rootzoll commented
replaced by improved PR #1616 ... will close this one

2020-10-07 10:52 UTC, closed without merging