Do not edit tor systemd script
raspiblitz/raspiblitz pull request #1506
Opened 2020-09-05 12:25 UTC by nolith

Systemd unit files under `/lib` should not be edited.

This commit will make use of
`/etc/systemd/system/tor@default.service.d/` to patch the system unit.

This should help also with #998

2020-09-05 19:23 UTC, frennkie requested changes
Please check

2020-09-05 19:23 UTC, frennkie commented on home.admin/config.scripts/internet.tor.sh
> +	sudo mkdir -p /etc/systemd/system/tor@default.service.d
Are you sure with this path? I found a tutorial and they are using `systemctl edit tor.service` which creates `/etc/systemd/system/tor.service.d/override.conf`. So this would then be `mkdir -p /etc/systemd/system/tor.service.d/`.

2020-09-05 19:23 UTC, frennkie commented on home.admin/config.scripts/internet.tor.sh
> +    echo -e "[Service]\nReadWriteDirectories=-/mnt/hdd/tor" | sudo tee -a /etc/systemd/system/tor@default.service.d/raspiblitz.conf
The default appears to be a file called `override.conf`. Works for me.

You are not changing anything regarding the Tor user... is this missing?

2020-09-05 19:54 UTC, frennkie commented
Please rename file to `override.conf` and put this in:

```
# RaspiBlitz modifications
[Service]
ExecStartPre=/usr/bin/install -Z -m 02755 -o bitcoin -g bitcoin -d /run/tor
ReadWriteDirectories=-/mnt/hdd/tor
```

2020-09-08 17:19 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +    echo -e "[Service]\nReadWriteDirectories=-/mnt/hdd/tor" | sudo tee -a /etc/systemd/system/tor@default.service.d/raspiblitz.conf
> You are not changing anything regarding the Tor user... is this missing? (Line ExecStartPre=/usr/bin/install -Z -m 02755 -o debian-tor -g debian-tor -d /run/tor)

I can't find this anywhere in raspiblitz scripts. I think it's part of the original script

> `ExecStartPre=/usr/bin/install -Z -m 02755 -o debian-tor -g debian-tor -d /run/tor`

2020-09-08 17:25 UTC, nolith commented
> Please rename file to `override.conf` and put this in:
> 
> ```
> # RaspiBlitz modifications
> [Service]
> ExecStartPre=/usr/bin/install -Z -m 02755 -o bitcoin -g bitcoin -d /run/tor
> ReadWriteDirectories=-/mnt/hdd/tor
> ```

I'll suggest to reconsider this idea.

`override.conf` is designed to be edited with `systemctl edit something.service`

Every file in `/etc/systemd/system/tor@default.service.d/` will be considered a Drop-In by systemd

```
sudo systemctl status tor@default
● tor@default.service - Anonymizing overlay network for TCP
   Loaded: loaded (/lib/systemd/system/tor@default.service; enabled-runtime; vendor preset: enabled)
  Drop-In: /etc/systemd/system/tor@default.service.d
           └─raspiblitz.conf
   Active: active (running) since Thu 2020-09-03 13:43:59 BST; 5 days ago
```

From my perspective here we have three players:
1. `tor` maintainers, providing `/lib/systemd/system/tor@default.service`
1. `raspiblitz` team, providing `/etc/systemd/system/tor@default.service.d/raspiblitz.conf`
1. the final user,  providing `/etc/systemd/system/tor@default.service.d/override.conf`

In this model file ownership is clear.

IMHO it's more effective than writing `# RaspiBlitz modifications` in `override.conf` hoping for the user to not edit it.

2020-09-08 17:27 UTC, nolith commented
Thank you @frennkie 

I've left some comments

2020-09-08 18:53 UTC, frennkie commented
> IMHO it's more effective than writing # RaspiBlitz modifications in override.conf hoping for the user to not edit it.

Makes sense to me! :-D

> I can't find this anywhere in raspiblitz scripts. I think it's part of the original script

My bad - you are right. I have the changes in mind that are listed [in this comment](https://github.com/rootzoll/raspiblitz/issues/998#issuecomment-599960455) - which I applied on my node - but wich are not yet part of the repo. 

Do you know how we could overrule this line in `/lib/systemd/system/tor@default.service`:

``` 
ExecStartPre=/usr/bin/install -Z -m 02755 -o debian-tor -g debian-tor -d /run/tor
```

2020-09-08 18:53 UTC, frennkie commented on home.admin/config.scripts/internet.tor.sh
> +	sudo mkdir -p /etc/systemd/system/tor@default.service.d
can you remove the 2 extra spaces?

2020-09-09 16:30 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +	sudo mkdir -p /etc/systemd/system/tor@default.service.d
🤦 it was not an extra space, but a line with spaces and one with a tab.

I should not edit code on the iPad and wait to be in front of a real computer.

It should be fixed now

2020-09-09 16:34 UTC, nolith commented
> Do you know how we could overrule this line in `/lib/systemd/system/tor@default.service`:
> 
> ```
> ExecStartPre=/usr/bin/install -Z -m 02755 -o debian-tor -g debian-tor -d /run/tor
> ```

It should be something like this (not tested)

```
[Service]
# reset ExecStartPre
ExecStartPre=
ExecStartPre=/usr/bin/install -Z -m 02755 -o bitcoin -g bitcoin -d /run/tor
ExecStartPre=/usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc -f /etc/tor/torrc --RunAsDaemon 0 --verify-config
```

But I will suggest to go down the router of hashed passwords like I wrote in https://github.com/rootzoll/raspiblitz/issues/998#issuecomment-687561682

2020-09-09 19:34 UTC, frennkie commented on home.admin/config.scripts/internet.tor.sh
> +    echo -e "[Service]\nReadWriteDirectories=-/mnt/hdd/tor" | sudo tee -a /etc/systemd/system/tor@default.service.d/raspiblitz.conf
One small thing: Can you please add `>/dev/null` at the end of 345 so that the two lines for the raspiblitz.conf file are not printed`.

2020-09-09 19:43 UTC, frennkie commented
> It should be something like this (not tested)

Yes.. that seems to work.

> But I will suggest to go down the router of hashed passwords like I wrote in #998 (comment)

That needs to be discussed.

2020-09-09 19:50 UTC, frennkie commented on home.admin/config.scripts/internet.tor.sh
> +    echo -e "[Service]\nReadWriteDirectories=-/mnt/hdd/tor" | sudo tee -a /etc/systemd/system/tor@default.service.d/raspiblitz.conf
Done

2020-09-09 19:52 UTC, frennkie approved these changes

2020-09-09 19:53 UTC, frennkie commented
LGTM 

@openoms ok with you?

@rootzoll is this also a candidate for `v1.6.1`?

2020-09-09 20:01 UTC, openoms commented
I like this. Needs to be tested, but would be happy with it in v1.6.1.

2020-09-10 11:52 UTC, rootzoll commented
will merge into dev and v1.6

2020-09-10 11:53 UTC, merged