Run tor with the default user
raspiblitz/raspiblitz pull request #1571
Opened 2020-09-20 14:15 UTC by nolith

This PR run tor as the default user and make use of hashed password for LND and bitcoind.

It fixes some of concerns in https://github.com/rootzoll/raspiblitz/issues/998

2020-09-20 14:17 UTC, nolith commented
@openoms do you mind a preliminary review? 🙏

2020-09-20 14:18 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +tor.password=$PASSWORD_B
This is fine to remain here in case of disactivation.

But it will not work if someone changes password b

2020-09-21 06:22 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +tor.password=$PASSWORD_B
Maybe instead of password b we should generate a password when we activate the feature?

Using password B has the advantage that a user can use it also from other software, while using a random one will require reading the cleartext password from `bitcoin.conf`, `lnd.conf`, or `.nyx/config`

2020-09-21 06:22 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +    sudo tee /etc/systemd/system/tor@default.service.d/raspiblitz.conf >/dev/null <<EOF
I think this is more clear and less error prone than the `grep` version.

This file is owned by `raspiblitz`.

Maybe we can add something like this:

```suggestion
    sudo tee /etc/systemd/system/tor@default.service.d/raspiblitz.conf >/dev/null <<EOF
    # DO NOT EDIT! This file is generate by raspiblitz and will be overwritten
```

2020-09-21 14:56 UTC, rootzoll commented
marked for v1.7 release @openoms if you think this is good to go already for v1.6.1 let me know

2020-09-21 15:28 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +
I don't think we should run nyx with the `bitcoin` user any more.

2020-09-21 15:30 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +tor.password=$PASSWORD_B
the solution is to change the Tor password when Password B is being changed just like with other services relying on it.
See the list around here: https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/config.scripts/blitz.setpassword.sh#L262

2020-09-21 15:33 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +    sudo mkdir -p /mnt/hdd/tor/bitcoin8332
```
    sudo mkdir -p /mnt/hdd/tor/web80
    sudo mkdir -p /mnt/hdd/tor/lnd9735
    sudo mkdir -p /mnt/hdd/tor/lndrpc9735
    sudo mkdir -p /mnt/hdd/tor/lndrest8080
    sudo mkdir -p /mnt/hdd/tor/lndrpc9735fallback
    sudo mkdir -p /mnt/hdd/tor/lndrest8080fallback
    sudo mkdir -p /mnt/hdd/tor/bitcoin8332
```
these folders are autogenerated by Tor on restart when the HIdden Service is configured in `torrc` so creating them is redundant (and it was also before)

2020-09-21 15:39 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +    sudo tee /etc/systemd/system/tor@default.service.d/raspiblitz.conf >/dev/null <<EOF
go for it, more comments are a good thing

2020-09-21 16:06 UTC, openoms commented
ok looking good.
tested on a testnet node.
PR 1571 checked out
deactivated Tor
```
sudo apt remove tor tor-arm
sudo rm -rf /etc/tor
```
reactivated Tor from the menu

Tor is running well, LND and bitcoin is functional.
Only nyx is not working with the `bitcoin` user for some reason.
`sudo nyx` works - shows warning about the unnecessary root permission
`sudo -u bitcoin nyx` is not showing the log despite the correct `password` given in `/home/bitcoin/.nyx/config`

If we can figure out Nyx would be happy to see this in v1.6.1 so we are not running tor as the `bitcoin` user any more.

2020-09-21 18:38 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +    sudo mkdir -p /mnt/hdd/tor/bitcoin8332
Thanks, removed

2020-09-21 18:38 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +tor.password=$PASSWORD_B
Thank you. Done

2020-09-21 18:40 UTC, nolith commented
@openoms I think the problem with the log was related an issue I fixed in the last commit.

Logrotate was creating the files as `bitcoin`

2020-09-22 15:22 UTC, openoms requested changes
`sudo -u debian-tor nyx`

now works well.

Just need to make sure that `nyx` is called with that user form the `00mainMenu.sh`

2020-09-22 15:22 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +tor.password=$PASSWORD_B
In case of a passwordB change:
* torrc would need a new HASHED_PASSWORD entry
* bitcoin.conf and lnd.conf would need the new Tor password (the RPC password is being changed there anyway)

2020-09-22 15:22 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +    HASHED_PASSWORD=$(tor --hash-password "$PASSWORD_B")
the script is run with sudo, so here we need to specify the user to run Tor otherwise it will be root.
use:
`HASHED_PASSWORD=$(sudo -u admin tor --hash-password "$PASSWORD_B")`


got this funny one in my torrc:
```
$ PASSWORD_B=test
admin@tBlitz:~ $ sudo -u admin tor --hash-password "$PASSWORD_B"
16:762FA966A54EDA5B6085909EA26BFB6BFCAF00576779DB34368CD3E36E
admin@tBlitz:~ $ sudo tor --hash-password "$PASSWORD_B"
Sep 22 16:15:49.895 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.
16:0CAE80B3D7B1D63E60D7722CB576FA1AB1A4C73E03EEEE747F486C7634
```

2020-09-23 06:37 UTC, nolith commented on home.admin/config.scripts/internet.tor.sh
> +    HASHED_PASSWORD=$(tor --hash-password "$PASSWORD_B")
It's expected to see differente outputs because there should be a salt in the hashed format that changes whern you generate it.

```
nolith@kitsune ~> tor --hash-password "foobar"
16:1F0EE7F6F5CD8F21600DD862B1662B21772ED6CCF0F0A87A4230EBDCB3
nolith@kitsune ~> tor --hash-password "foobar"
16:93D47C0497ADC30E609ACD5727A8BC27AA9C71C9F76127F80D9D616E80
nolith@kitsune ~> tor --hash-password "foobar"
16:03032718E1D0406660359658F467DC6FF146A5844BB2BDCD0D57288CC5
nolith@kitsune ~> tor --hash-password "foobar"
16:889188205C83B649608AF74E2E1EF742EEF05E07AA50840C3E18F0EB2A
```

> Sep 22 16:15:49.895 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.

This should be part of stderr as it didn't ended up on my config files when I tested renaming.

So from a functional point of view, it works. But I do agree it will be better to run it with the proper user

2020-09-23 06:40 UTC, nolith commented
> `sudo -u debian-tor nyx`
> 
> now works well.
> 
> Just need to make sure that `nyx` is called with that user form the `00mainMenu.sh`

Maybe I got it wrong here. I made it so that we can run `nyx` with the `bitcoin` user, as it is today in `00mainMenu.sh`.

If I had to follow my personal taste, I would have preferred not using `bitcoin` user but make it work with `admin` only. `nyx` is clearly an admin monitoring tool, if we have to change `00mainMenu.sh` I'll suggest we make it so it's the `admin` that runs it.

WDYT @openoms ?

2020-09-23 06:46 UTC, openoms commented
debian-tor is perfect to run nyx.
Admin has passwordless sudo access so avoid it as much as possible. It is the user facing user.
Bitcoin has the ROC password and access to wallets so would not use it for nyx either. It was only used because Tor was running with bitcoin.
Segrating these is a very welcome change 👍

2020-09-23 10:30 UTC, openoms commented
Since testing on restart I get the Tor error:
```
 $ sudo systemctl status tor@default
● tor@default.service - Anonymizing overlay network for TCP
   Loaded: loaded (/lib/systemd/system/tor@default.service; enabled-runtime; vendor preset: enabled)
  Drop-In: /etc/systemd/system/tor@default.service.d
           └─raspiblitz.conf
   Active: failed (Result: exit-code) since Wed 2020-09-23 11:28:00 BST; 11s ago
  Process: 25190 ExecStartPre=/usr/bin/install -Z -m 02755 -o debian-tor -g debian-tor -d /run/tor (code=exited, status=0/SUCCESS)
  Process: 25191 ExecStartPre=/usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc -f /etc/tor/torrc --RunAsDaemon 0 --verify-config (code=exited, status=1/FAILURE)

Sep 23 11:28:00 tBlitz systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Sep 23 11:28:00 tBlitz systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
Sep 23 11:28:00 tBlitz systemd[1]: Stopped Anonymizing overlay network for TCP.
Sep 23 11:28:00 tBlitz systemd[1]: tor@default.service: Start request repeated too quickly.
Sep 23 11:28:00 tBlitz systemd[1]: tor@default.service: Failed with result 'exit-code'.
Sep 23 11:28:00 tBlitz systemd[1]: Failed to start Anonymizing overlay network for TCP.
```
not sure what it is about, will need to investigate. Would need a clean install, but have no time currently.
Can you have a look if you can reproduce?

2020-09-24 20:32 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +    HASHED_PASSWORD=$(tor --hash-password "$PASSWORD_B")
Still having this issue causing the failure:
```
 $ sudo -u debian-tor /usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc -f /etc/tor/torrc --RunAsDaemon 0 --verify-config
Sep 24 21:29:18.940 [notice] Tor 0.4.2.7 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Sep 24 21:29:18.940 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Sep 24 21:29:18.940 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Sep 24 21:29:18.940 [notice] Read configuration file "/etc/tor/torrc".
Sep 24 21:29:18.942 [warn] Failed to parse/validate config: Unknown option '16:F2A2286AC63B1D3760D6E9F2B6C3C1E1ED3684CD7F87947317BD33E006'.  Failing.
Sep 24 21:29:18.942 [err] Reading config failed--see warnings above.
```
Not surprised since my torrc has this:
```
...
ExitRelay 0

HashedControlPassword Sep 24 21:24:23.090 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.
16:F2A2286AC63B1D3760D6E9F2B6C3C1E1ED3684CD7F87947317BD33E006

# Hidden Service for WEB ADMIN INTERFACE
...
```

2020-09-24 20:37 UTC, openoms requested changes
Still need to use:
```
HASHED_PASSWORD=$(sudo -u admin tor --hash-password "$PASSWORD_B")
```
in line 288

2020-09-24 20:37 UTC, openoms commented on home.admin/config.scripts/internet.tor.sh
> +    HASHED_PASSWORD=$(tor --hash-password "$PASSWORD_B")
Still need to use:
```
HASHED_PASSWORD=$(sudo -u admin tor --hash-password "$PASSWORD_B")
``` 
in line 288

2020-09-28 17:30 UTC, nolith reviewed
Now everything should run as `debian-tor`

2020-09-28 17:30 UTC, nolith commented on home.admin/00mainMenu.sh
> +            sudo -u debian-tor nyx
Changing this allowed us to avoid creating a nyx config file 🎉

2020-09-28 18:27 UTC, openoms approved these changes

2020-09-28 19:03 UTC, openoms commented
ok, works great `tACK`

![image](https://user-images.githubusercontent.com/43343391/94474450-954d7a80-01c5-11eb-8b55-dc66423d796c.png)

@rootzoll what do you think of including it to v1.6.1?

2020-09-28 19:10 UTC, openoms commented
Tested the password change too, works OK.
`apt upgrade` should not be a problem any more either.

2020-09-28 19:25 UTC, rootzoll commented
> @rootzoll what do you think of including it to v1.6.1?

LGTM lets do this ... including into my v1.6.1 test-runs.

2020-09-28 19:26 UTC, merged

2020-09-28 21:08 UTC, rootzoll commented
Then recovering/updating a RaspiBlitz with this new PR - LND is not starting anymore. I get:
![Bildschirmfoto 2020-09-28 um 23 05 23](https://user-images.githubusercontent.com/2472225/94486275-79ef6900-01df-11eb-813d-275ddd78513d.png)

2020-09-28 21:16 UTC, openoms commented
it should have the tor password in lnd.conf and not look for the cookie :/

2020-09-29 06:55 UTC, openoms commented
https://github.com/lightningnetwork/lnd/blob/master/docs/configuring_tor.md
```
 --tor.password=  The password used to arrive at the HashedControlPassword for the control port. If provided, the HASHEDPASSWORD authentication method will be used instead of the SAFECOOKIE one.
```

Check for `HashedControlPassword` in `/etc/tor/torrc` and `tor.password=PASSWORD_B` in `/mnt/hdd/lnd/lnd.conf`

2020-09-30 18:18 UTC, rootzoll commented
OK the problem is when I update/recover a node running on old Tor settings with the new script. Then I have the following situation:

- lnd.conf has no Tor password in it
- bitcoin.conf has no password in it
- tor conf has the password set

I will check how to make sure this is also working in recovery/update from old state.

2020-09-30 19:43 UTC, rootzoll commented
OK now also on recovery/update from the old configs this works with my latest merge.

2020-09-30 20:26 UTC, nolith commented
Thanks for fixing this. 

So the problem was that finding an old conf on recovery it was not updating it with the tor password?

2020-09-30 20:29 UTC, rootzoll commented
> So the problem was that finding an old conf on recovery it was not updating it with the tor password?

Yes. With LND that was due to an outside script thing. Should be working now.

2020-10-01 20:39 UTC, theotherside commented
LTND: unable to initialize tor controller: HASHEDPASSWORD authentication method not supported

2020-10-03 14:39 UTC, openoms commented
> LTND: unable to initialize tor controller: HASHEDPASSWORD authentication method not supported

you need at least lnd v0.10.0. Uodate form the UPDATE menu
https://github.com/lightningnetwork/lnd/releases/tag/v0.10.0-beta