faq cleanup
raspiblitz/raspiblitz pull request #2668
Opened 2021-10-26 16:07 UTC by nyxnor

Organized by topics, update, ssh, debug, dev, extras.

https://github.com/nyxnor/raspiblitz/blob/faq-cleanup/FAQ.md

## Image
![image](https://user-images.githubusercontent.com/69700936/138918309-08ada32c-b416-4708-a252-862da0c829bf.png)

2021-10-26 21:19 UTC, openoms commented
LGTM!

2021-10-28 16:19 UTC, openoms commented
ACK a65e213

2021-11-11 15:57 UTC, rootzoll requested changes
please see comments on code to checked before merge

2021-11-11 15:57 UTC, rootzoll commented on FAQ.md
> +Using pre-built software almost always shifts trust to the one who made the binary. But at least you can check with the SHA checksum after downloading to verify that the image downloaded is really th
> Still, this is not optimal and if at least some people from the community request it, I will consider signing the download as an author for the future

Every official download is signed ... for example here is the signature file for the v1.7.1 release:
https://raspiblitz.fulmo.org/images/raspiblitz-v1.7.1-2021-10-28.img.gz.sig

The only exceptions that dont have a signature file are Release Canidates on the dev branches.

2021-11-11 15:57 UTC, rootzoll commented on FAQ.md
> +### How do I upgrade my RaspiBlitz?
Changing the headline text might break links to this chapter .. for example from README. To be checked.

2021-11-11 15:57 UTC, rootzoll commented on FAQ.md
> +## Debug
The next three questioins are about LCD ... I would put them into a seperate section called "Display" instead of having them in "Debug"

2021-11-11 15:57 UTC, rootzoll commented on FAQ.md
> +### How do I find the IP address when running without a display?
This can then also be under "Display" section.

2021-11-11 15:57 UTC, rootzoll commented on FAQ.md
> +* Minor Updates: 1.1.0, 1.2.0, 1.3.0, ... are soft updates - can be done by 'patching' the scripts & code, but new sd card reflash is still advised.
Minor Updates: 1.3.1, 1.3.2, 1.3.3

2021-11-18 22:44 UTC, nyxnor commented on FAQ.md
> +Using pre-built software almost always shifts trust to the one who made the binary. But at least you can check with the SHA checksum after downloading to verify that the image downloaded is really th
does Mac have `sha256sum` command instead of `shasum -a 256`?

2021-11-18 22:53 UTC, nyxnor commented on FAQ.md
> +### How do I upgrade my RaspiBlitz?
ok.
Just as a point, when using `apt update`, we update the local package index based on the sources, when using `apt upgrade`, we use the local package index to request to the source that package version. So if chaning blitz version, you are upgrading to a new version, and seeing the new blitz version on github kinda is updating your mind database index.

2021-11-29 19:24 UTC, rootzoll approved these changes

2021-11-29 19:32 UTC, merged