set hostname on x86_64
raspiblitz/raspiblitz pull request #2831
Opened 2021-12-20 21:29 UTC by adevoss

Hostname is only set on Raspberry Pi.
Maybe a cosmetic thing only.
Maybe related to #2813

2021-12-21 12:13 UTC, adevoss commented
Another option is to not using `raspi-config` for setting the hostname

2021-12-21 14:27 UTC, rootzoll requested changes

2021-12-21 14:27 UTC, rootzoll commented on home.admin/_provision_.sh
> +      if [ "${baseimage}" == "raspbian" ]; then
the standard baseimage on raspberrypi is "raspios_arm64"

2021-12-21 16:18 UTC, adevoss commented
Made the change.
Should I have approved your request? Don't see such an option in the GitHub web interface.

2021-12-22 15:40 UTC, adevoss commented
Tested fresh install with `dev` branch.
Hostname is changed on my Debian VM.

2021-12-23 13:48 UTC, merged