Improve localIP assignment and SSD detection
raspiblitz/raspiblitz pull request #3439
Opened 2022-11-14 20:00 UTC by rek79

**Rebased PR #3424 from [rootzoll/raspiblitz](https://github.com/rootzoll/raspiblitz) to [dev ](https://github.com/rootzoll/raspiblitz/tree/dev) branch**
**Fix localip assignment:**
use `localip=$(hostname -I | awk '{print $1}')` in place of `localip=$(ip addr | grep 'state UP' -A2 | grep -E -v 'docker0|veth' | grep 'eth0\|wlan0\|enp0' | tail -n1 | awk '{print $2}' | cut -f1 -d'/')`.
The former assignment seems to work on a wider range of hardware.
related: https://github.com/rootzoll/raspiblitz/commit/5d61d0b216b281ff7b99e0488c39390d1d5e038c#commitcomment-89042523

**Improve reliability of solid state drive detection:**
smartctl seems to be more compatible with a wider array of hardware.
`isSSD=$(cat /sys/block/${hdd}/queue/rotational 2>/dev/null | grep -c 0)` incorrectly sets SSD to false for Odroid HC2. `isSSD=$(sudo smartctl -a /dev/sda | grep 'Rotation Rate:' | grep -c "Solid State")` correctly identifies the SSD.
Related issue: https://github.com/rootzoll/raspiblitz/issues/3423#issue-1439092806

2022-11-15 13:43 UTC, rek79 commented
@rootzoll should be all set to test now that the PR is based on `dev` .

2022-11-16 15:17 UTC, ChuckNorrison commented
[wifilocalIP](https://github.com/rootzoll/raspiblitz/pull/3439/commits/3e48433322bdecbba2353fe509e275ea7851b80c) is still wrong and with the wildcard it will print the LAN IP instead nothing, if wifi is not used

2022-11-19 17:33 UTC, rek79 commented
> [wifilocalIP](https://github.com/rootzoll/raspiblitz/pull/3439/commits/3e48433322bdecbba2353fe509e275ea7851b80c) is still wrong and with the wildcard it will print the LAN IP instead nothing, if wifi is not used

Is it as simple as changing it to: `hostname -I | awk '{print $1}'`

2022-11-19 18:18 UTC, ChuckNorrison commented
Just remove the wildcard (*) from the IP addr command to get the wifi IP. You can check if it prints your lan ip, it should not print your lan ip. Should be empty without wifi used

2022-11-19 18:48 UTC, rek79 commented
@ChuckNorrison Okay, reverted back to original.  Should be all set now.

2022-11-21 19:10 UTC, rootzoll requested changes

2022-11-21 19:10 UTC, rootzoll commented on home.admin/config.scripts/blitz.datadrive.sh
> +smartmontoolsInstalled=$(dpkg -s smartmontools 2>/dev/null | grep -c "install ok installed")
Is there a special reason ti use `dpkg` instead of `apt-get`? `apt-get` would also check for missing dependencies (may be needed on other base OS) and so be more error blocking prone.

2022-11-21 19:10 UTC, rootzoll commented on home.admin/config.scripts/blitz.datadrive.sh
>      echo "isSSD=${isSSD}"
Would recommend to also echo "isSMART" here for better debug.

2022-11-21 19:10 UTC, rootzoll commented on home.admin/config.scripts/blitz.datadrive.sh
>      echo "isSSD=${isSSD}"
Would recommend to also echo "isSMART" here for better debug.

2022-11-23 17:08 UTC, rek79 commented on home.admin/config.scripts/blitz.datadrive.sh
> +smartmontoolsInstalled=$(dpkg -s smartmontools 2>/dev/null | grep -c "install ok installed")
> 

I was attempting to follow the same coding pattern as:
https://github.com/rootzoll/raspiblitz/blob/b8a9c84845d40ea786e48f94cac9e0d927c4b026/home.admin/config.scripts/blitz.datadrive.sh#L29-L39

I could just call `apt-get install` and do away with pre-checking if the package is installed.  Are you suggesting we go that route? Or, is there a way to pre-check if the package is installed using apt-get?

2022-11-23 17:08 UTC, rek79 commented on home.admin/config.scripts/blitz.datadrive.sh
>      echo "isSSD=${isSSD}"
ACK, done.

2022-11-24 15:02 UTC, rootzoll commented on home.admin/config.scripts/blitz.datadrive.sh
> +smartmontoolsInstalled=$(dpkg -s smartmontools 2>/dev/null | grep -c "install ok installed")
basically - because blitz.datadrive.sh is a very basic always needed script - the dependency can also move into the sd card build script. https://github.com/rootzoll/raspiblitz/blob/8e3fef2144f0cc2810d0278b62fb08eb36d88ab2/build_sdcard.sh#L305

2022-11-29 17:19 UTC, rek79 commented on home.admin/config.scripts/blitz.datadrive.sh
> +smartmontoolsInstalled=$(dpkg -s smartmontools 2>/dev/null | grep -c "install ok installed")
Replaced `dpkg -s smartmontools 2>/dev/null | grep -c "install ok installed"` with `apt-cache policy smartmontools | grep -c 'Installed: (none)' | grep -c "0"`
Added smartmontools to general_utils.

2022-12-08 10:04 UTC, rootzoll approved these changes

2022-12-08 11:19 UTC, rootzoll approved these changes

2022-12-08 11:20 UTC, merged