Update README.md
raspiblitz/raspiblitz pull request #3472
Opened 2022-11-22 22:53 UTC by TnTBass

Clarified static channel backups and made one section instead of two

2022-11-22 23:44 UTC, rootzoll approved these changes

2022-11-22 23:46 UTC, rootzoll requested changes

2022-11-22 23:46 UTC, rootzoll commented on README.md
> +See [SCP Backup Target](https://github.com/rootzoll/raspiblitz/blob/baa2ca485d11f84cbfd90778813b8ec07f38e84d/README.md#b-scp-backup-target) for details on how to setup static channel backups using SC
The Link looks here a bit too specific to .. would use just a shart/generic Link here so that it ends up in the same document .. not another old one in the repo.

2022-11-23 20:53 UTC, TnTBass commented on README.md
> +See [SCP Backup Target](https://github.com/rootzoll/raspiblitz/blob/baa2ca485d11f84cbfd90778813b8ec07f38e84d/README.md#b-scp-backup-target) for details on how to setup static channel backups using SC
I should have caught that, sorry about that. Its fixed.

2022-11-24 13:57 UTC, rootzoll approved these changes

2022-11-24 13:58 UTC, merged