Lnd fixes
raspiblitz/raspiblitz pull request #3986
Opened 2023-07-02 10:02 UTC by openoms

Related: #3885

2023-07-02 18:06 UTC, cstenglein requested changes

2023-07-02 18:06 UTC, cstenglein commented on home.admin/config.scripts/lnd.check.sh
> +  sudo sed -i '/^  \[rpcmiddleware\]/d' ${lndConfFile}
I think this won't remove the [[Rr]pcmiddleware] lines in the config file:

![IMG_20230702_192842_321.jpg](https://github.com/raspiblitz/raspiblitz/assets/9399034/0c71b9ef-87e0-4e79-9027-10fde9ab5385)

2023-07-02 20:18 UTC, openoms commented on home.admin/config.scripts/lnd.check.sh
> +  sudo sed -i '/^  \[rpcmiddleware\]/d' ${lndConfFile}
Thanks, can't hurt if we make sure those are gone too:
```suggestion
  sudo sed -i '/^  \[\[Rr\]pcmiddleware\]/d' ${lndConfFile}
```

2023-07-03 18:49 UTC, cstenglein approved these changes

2023-07-08 12:53 UTC, rootzoll approved these changes

2023-07-08 12:53 UTC, merged