Changed version of BTCPayServer to 1.12.0
raspiblitz/raspiblitz pull request #4334
Opened 2023-12-21 01:06 UTC by kravens

Updated dependency NBXplorer to: https://github.com/dgarage/NBXplorer/releases/tag/v2.4.3 and .NET to 8.0.100.
Need some help to get the GPG check working for this version.

```# running: git verify-commit 6ecfe073e

gpg: Signature made Tue 19 Dec 2023 11:58:52 GMT
gpg:                using RSA key 836C08CF3F523BB7A8CB8ECF8E5530D9D1C93097
gpg: Can't check signature: No public key
# goodSignature(0)
# correctKey(0)

# BUILD FAILED --> PGP verification not OK / signature(0) verify(0)```

2023-12-21 15:27 UTC, cstenglein requested changes
Thank you for the contribution!

You accidentally deleted too much code, that's the reason the check failed.

2023-12-21 15:27 UTC, cstenglein commented on home.admin/config.scripts/bonus.btcpayserver.sh
> -# check who signed the release (person that published release)
Please don't delete that part so the signature check can be performed.

2023-12-22 00:12 UTC, kravens commented on home.admin/config.scripts/bonus.btcpayserver.sh
> -# check who signed the release (person that published release)
Just fixed any excess deleted lines versus the dev branch script, maybe someone can test this and see if it builds without verification error?

2023-12-22 18:12 UTC, openoms commented on home.admin/config.scripts/bonus.btcpayserver.sh
> +BTCPayVersion="v1.12.0"
Looks good now, but can we go with the latest now: https://github.com/btcpayserver/btcpayserver/releases/tag/v1.12.3

There have been a few bugfixes.

2023-12-22 18:13 UTC, openoms commented on home.admin/config.scripts/bonus.btcpayserver.sh
> +exit 1
just add a new line here

2023-12-23 08:11 UTC, openoms commented on home.admin/config.scripts/bonus.btcpayserver.sh
> +BTCPayVersion="v1.12.0"
![image](https://github.com/raspiblitz/raspiblitz/assets/43343391/067b8178-9088-4219-a054-57883e49a0c8)
the commit for the v1.12.3 release was created on github so will need to change the signer to web-flow.

Otherwise the script install runs through successfully.
Thanks for updating the .Net

2023-12-23 08:44 UTC, openoms commented on home.admin/config.scripts/bonus.btcpayserver.sh
> +BTCPayVersion="v1.12.0"
can modify this afterwards

2023-12-23 08:44 UTC, openoms commented on home.admin/config.scripts/bonus.btcpayserver.sh
> +exit 1
just a nit, noted for the future

2023-12-23 08:45 UTC, openoms approved these changes

2023-12-23 08:47 UTC, merged