mempool update to v2.5.0
raspiblitz/raspiblitz pull request #4353
Opened 2024-01-06 14:35 UTC by openoms

fixes: #4352

2024-01-13 21:09 UTC, cstenglein commented on home.admin/config.scripts/bonus.mempool.sh
> +  if ! sudo -u mempool NG_CLI_ANALYTICS=false npm install --no-optional; then
Better use 
```npm ci```

2024-01-13 21:09 UTC, cstenglein commented on home.admin/config.scripts/bonus.mempool.sh
> +  if ! sudo -u mempool NG_CLI_ANALYTICS=false npm install --no-optional; then
npm ci

2024-01-13 21:09 UTC, cstenglein commented on home.admin/config.scripts/bonus.mempool.sh
> +  if ! sudo -u mempool NG_CLI_ANALYTICS=false npm run build; then
Instead of repeating the ng analytics command you could export it

export NG_CLI_ANALYTICS="false"

2024-01-13 22:03 UTC, openoms commented on home.admin/config.scripts/bonus.mempool.sh
> +  if ! sudo -u mempool NG_CLI_ANALYTICS=false npm run build; then
not sure of that works when running the command with a different user

2024-01-13 22:11 UTC, openoms commented on home.admin/config.scripts/bonus.mempool.sh
> +  if ! sudo -u mempool NG_CLI_ANALYTICS=false npm install --no-optional; then
will test if that does make a difference with the failing angular build discussed in #4352

2024-01-14 08:03 UTC, openoms commented on home.admin/config.scripts/bonus.mempool.sh
> +  if ! sudo -u mempool NG_CLI_ANALYTICS=false npm install --no-optional; then
awesome that worked. Changed in https://github.com/raspiblitz/raspiblitz/pull/4353/commits/6232b6f41b73124717b6b9c6ada61e928080c90d

2024-01-14 08:17 UTC, cstenglein requested changes

2024-01-14 08:17 UTC, cstenglein commented on home.admin/config.scripts/bonus.mempool.sh
> +    if ! sudo -u mempool NG_CLI_ANALYTICS=false npm install; then
```suggestion
    if ! sudo -u mempool NG_CLI_ANALYTICS=false npm ci; then
```

2024-01-14 08:17 UTC, cstenglein commented on home.admin/config.scripts/bonus.mempool.sh
> +    if ! sudo -u mempool NG_CLI_ANALYTICS=false npm install; then
```suggestion
    if ! sudo -u mempool NG_CLI_ANALYTICS=false npm ci; then
```

2024-01-14 08:19 UTC, cstenglein commented
When installing mempool with that script, it works, but it doesn't add it to the menu & doesn't tick the box in the menu.

2024-01-14 08:44 UTC, openoms commented
> When installing mempool with that script, it works, but it doesn't add it to the menu & doesn't tick the box in the menu.

can't reproduce this, works well now on amd64 and rpi5

2024-01-14 09:53 UTC, cstenglein commented
> > When installing mempool with that script, it works, but it doesn't add it to the menu & doesn't tick the box in the menu.
> 
> can't reproduce this, works well now on amd64 and rpi5

Installed it over the command line.

Worked when installing over the menu => OK

2024-01-14 09:53 UTC, cstenglein approved these changes

2024-01-14 09:54 UTC, cstenglein commented
To merge you'll need the approval of a codeowner => @rootzoll

2024-01-15 18:43 UTC, merged